apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-jenkins_helm
  namespace: jenkins_helm
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/server-alias: {{ index .Values "host" "second_host" }}
spec:
  rules:
    - host: {{ index .Values "host" "main_host" }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jenkins_helm
                port:
                  number: {{ index .Values "containerPort" "http-port" }}
